### ISSUE TITLE
【关于】页面的卡片视图在移动端显示有问题

### ISSUE THREAD

**Issue by leonxcom** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#175]
【相关网址】https://blog.wakehuang.com/about/

【问题1】移动端显示的红框处无法填充完整
<img width="404" alt="image" src="https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/14356434/decff80b-c6b2-4678-81e6-587f63859443">

【问题2】移动端的一些卡片没有自适应显示全图

<img width="366" alt="image" src="https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/14356434/13bdc8a6-bc43-4294-aa76-c39d218675ec">

【问题3】主题配置文件的`about.yml`配置失效，红框处的配置项`tips`配置后无法显示
<img width="469" alt="image" src="https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next/assets/14356434/63ab5a70-0bb2-455a-bb1c-9c20e244cdfd">

【建议解决方案】参考Heo的关于页面：
https://blog.zhheo.com/about/

**Comment by everfu** [comment]
修改主题css：main.css 文件
第13255行开始，或者查找：`.author-content-item>img`
```css
.author-content-item>img{
  object-fit: fill;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1;
  object-position: no-repeat top;
}
```
原来的：
```css
.author-content-item>img{
  object-fit: cover;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1;
  object-position: no-repeat top;
}
```
```xml
object-fit: cover -> object-fit: fill
```
将整个元素占满吧，可能会把原图拉伸，建议上传同等大小的图片
