### ISSUE TITLE
关于友情链接添加的方式

### ISSUE THREAD

**Issue by everfu** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#188]
您好，我有一个疑惑，为啥要单独开一个banner进行添加，一个友链需要分别添加到banner和内容中，是不是可以节省一下，直接使用links中`type`为`item`的友链作为banner展示？或者说可以手动添加一个属性，把需要在banner中展示的友链进行标记，然后展示到banner内容中？这样节省了后期删除友链带来的麻烦。

我简单的实现了一下`type`为`item`的友链在banner中显示。
```ejs
<div class="banners-title">
    <div class="banners-title-small"><%= page.title %></div>
    <div class="banners-title-big"><%= page.desc %></div>
</div>
<div class="banner-button-group">
    <% if (theme.footer.randomlink){ %>
        <a class="banner-button secondary" onclick="travelling()">
            <i class="fas fa-shuffle"></i>
            <span class="banner-button-text">随机访问</span>
        </a>
    <% } %>
    <a class="banner-button" onclick="acrylic.scrollToComment()">
        <i class="fas fa-circle-chevron-right"></i>
        <span class="banner-button-text">申请友链</span>
    </a>
</div>
<div class="tags-group-all nowrapMove">
    <div class="tags-group-wrapper">
-       <% const data = site.data.links.banner %>
-       <% for(let i = 1; i <= 2; i++){ %>
-        <% for (let i = 0; i < Math.ceil(data.length / 2); i++) { %>
-          <div class="tags-group-icon-pair">
-            <% for (let j = i * 2; j < Math.min(data.length, i * 2 + 2); j++) { %>
-              <a class="tags-group-icon" href="<%= url_for(data[j].link) %>" title="<%= data[j].name %>">
-                <img src="<%= data[j].avatar %>" title="<%= data[j].name %>">
-              </a>
-            <% } %>
-          </div>
-        <% } %>
-      <% } %>
+        <% const data = site.data.links.links %>
+        <% for (let i = 0; i < 2; i++){ %>
+            <% data.forEach(x => {
+            if (x.type === "item") {
+            x.link_list.forEach((y, index) => { %>
+                <% if(index % 2 === 0){ %>
+                <div class="tags-group-icon-pair">
+                    <% } %>
+                    <a class="tags-group-icon" href="<%= url_for(y.link) %>" title="<%= y.name %>">
+                        <img src="<%= y.avatar %>" title="<%= y.name %>">
+                    </a>
+                    <% if(index % 2 !== 0 || index === x.link_list.length - 1){ %>
+                </div>
+                <% } %>
+            <% })
+            }
+            }) %>
+        <%}%>
    </div>
</div>
```

**Comment by everfu** [comment]
或者通过另外一种，通过给友链添加属性`banner`值为布尔
```yaml
  - class_name: 技术
    descr: 技术知识为主的博客
    type: item
    link_list:
      - name: 张洪Heo
        link: https://blog.zhheo.com/
        avatar: https://bu.dusays.com/2022/12/28/63ac2812183aa.png
        descr: 分享设计与科技生活
        rss: /rss.xml
        tag: 荐
        vip: true
        banner: true
      - name: Rootlex
        link: https://blog.nalex.top/
        avatar: https://bu.dusays.com/2023/01/25/63d130a6ce9ea.jpg
        descr: 寒蝉黎明之时，便是重生之日
        rss: /atom.xml
        tag: 荐
        vip: true
       banner: true
```
