### ISSUE TITLE
友链样式出错

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#36]
- 问题：友链配置太少会样式出错
- 配置

```yml
banner:
  - name: Akilar
    link: https://akilar.top
    avatar: https://bu.dusays.com/2022/08/14/62f87864834ae.png

links:
  - class_name: 大佬们
    descr: 一些大佬
    type: card
    link_list:
      - name: Akilar
        link: https://akilar.top
        avatar: https://bu.dusays.com/2022/08/14/62f87864834ae.png
        topimg: /img/acrylic.png
        descr: 欢迎光临糖果屋
        rss: /atom.xml

  - class_name: 朋友们
    descr: 一些志同道合的朋友
    type: item
    link_list:
      - name: Tianli
        link: https://tianli-blog.club
        avatar: https://img1.tianli0.top/logo.png
        descr: 惟其不可能，所以才相信。
        rss: /feed/
```
- 效果
![image](https://user-images.githubusercontent.com/22308895/225802113-5ca3403f-47b3-48d9-8ffc-9a2e4da8f908.png)
