### ISSUE TITLE
说说时间显示为 NaN

### ISSUE THREAD

**Issue by cunyu1943** [hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next#46]
- 配置

```yml
- content: 终于把博客搭建完成了！
  date: 2023-03-16 08:00:00
  link: https://cunyu1943.githu.io
```
- 显示
<img width="432" alt="image" src="https://user-images.githubusercontent.com/22308895/226171348-ed1d4202-d28c-4aca-8d7f-bc33dd014f88.png">
